insert into Address(country, state) values ('USA','Florida');
insert into Address(country, state) values ('USA','Maine');
insert into Address(country, state) values ('USA','New Mexico');
insert into Address(country, state) values ('USA','Texas');
insert into Address(country, state) values ('USA','Wyoming');
insert into Address(country, state) values ('USA','Wyoming');
insert into Address(country, state) values ('USA','Utah');
insert into Address(country, state) values ('USA','Oklahoma');
insert into Address(country, state) values ('USA','Oklahoma');
insert into Address(country, state) values ('USA','North Dakota');
insert into Address(country, state) values ('USA','North Dakota');
insert into Address(country, state) values ('USA','North Carolina');
insert into Address(country, state) values ('USA','North Carolina');
insert into Address(country, state) values ('USA','Mississippi');
insert into Address(country, state) values ('USA','Mississippi');
insert into Address(country, state) values ('USA','Mississippi');
insert into Address(country, state) values ('Turkey','İzmir');
insert into Address(country, state) values ('Turkey','Adana');
insert into Address(country, state) values ('Turkey','Urfa');
insert into Address(country, state) values ('Turkey','Mersin');
insert into Address(country, state) values ('Turkey','İstanbul');
insert into Address(country, state) values ('Turkey','İstanbul');
insert into Address(country, state) values ('Turkey','İstanbul');
insert into Address(country, state) values ('Turkey','Ankara');
insert into Address(country, state) values ('Turkey','Ankara');
insert into Address(country, state) values ('Turkey','Ankara');
insert into Address(country, state) values ('Turkey','Kocaeli');
insert into Address(country, state) values ('Turkey','Kocaeli');
insert into Address(country, state) values ('Turkey','Düzce');
insert into Address(country, state) values ('Turkey','Trabzon');
insert into Address(country, state) values ('Turkey', 'İstanbul');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('Turkey', 'İstanbul');
insert into Address(country, state) values ('USA', 'Oklahoma');
insert into Address(country, state) values ('USA', 'Oklahoma');
insert into Address(country, state) values ('USA', 'Texas');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İstanbul');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('Turkey', 'İstanbul');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('England', 'Manchester');
insert into Address(country, state) values ('England', 'Chelsea');
insert into Address(country, state) values ('England', 'Manchester');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('USA', 'Texas');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İstanbul');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İzmir');
insert into Address(country, state) values ('Turkey', 'Bursa');
insert into Address(country, state) values ('Turkey', 'İstanbul');