insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (1,'Bilgisayar Mühendisliği','Matt','','Stones', 1, 4);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (2,'Kimya Mühendisliği','Lucca','','Berg', 2, 12);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (3,'Makine Mühendisliği','Shantelle','','Greenwood',null, 15);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (4,'Elektrik Mühendisliği','Fay','','Hardy',null, 11);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (5,'Gıda Mühendisliği','Hari','','Crouch', 3, 20);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (6,'Peysaj Mühendisliği','Humairaa','','Zamora',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (7,'Kimya Mühendisliği','Lindsay','','Morin',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (8,'Makine Mühendisliği','Ellis','','Eastwood', 4, 13);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (9,'Bilgisayar Mühendisliği','Trinity','','Walsh',null, 5);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (10,'Gıda Mühendisliği','Robbie','','Rooney', 5, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (11,'Elektrik Mühendisliği','Vivek','','Russell', 6, 28);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (12,'Endüstri Mühendisliği','Monica','','Key',7, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (13,'Endüstri Mühendisliği','Bruce','','Tucker',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (14,'Endüstri Mühendisliği','Blade','','Pitts', 8, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (15,'Kimya Mühendisliği','Corey','','Crane',9, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (16,'Kimya Mühendisliği','Sherri','','Wiley',10, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (17,'Bilgisayar Mühendisliği','Amy','L','Reeves',null, 7);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (18,'Gıda Mühendisliği','Ffion','','Garner',11, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (19,'Peysaj Mühendisliği','Korey','','Riddle',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (20,'Peysaj Mühendisliği','Mohamad','','Randall',12, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (21,'Gıda Mühendisliği','Aryan','','Simmonds',13, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (22,'Kimya Mühendisliği','Keelan','','Bradley',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (23,'Kimya Mühendisliği','Sheikh','','Ellis',14, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (24,'Makine Mühendisliği','Macaulay','','Robins',15, 28);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (25,'Çevre Mühendisliği','Jazmyn','','Walter',16, 23);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (26,'Çevre Mühendisliği','Tashan','','Huynh',null, 26);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (27,'Çevre Mühendisliği','Jake','','Mitchell',17, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (28,'Kimya Mühendisliği','Asia','','Booker',18, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (29,'Kimya Mühendisliği','Kaden','','Winters',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (30,'Makine Mühendisliği','Autumn','','Akhtar',19, 18);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (31,'Matematik','Hayri','M','Başaran',20, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (32,'Matematik','Mehmet','A','Güleryüz',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (33,'Pilot','Fehmi','C','Koç',21, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (34,'Mekatronik Mühendisliği','Ali','O','Akman',null, 19);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (35,'Doktor','Callum','H','Odoi',22, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (36,'Mekatronik Mühendisliği','Shane','L','Larkin',23, 30);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (37,'Sporcu','Lewis','S','Hamilton',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (38,'Matematik','Mustafa','A','Güç',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (39,'İnşaat Mühendisliği','Ferman','B','Yaşar',null, 29);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (40,'Mekatronik Mühendisliği','Levent','M','Suskun',24, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (41,'Öğretmen','Kerim','F','Aslan',25, 1);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (42,'Öğretmen','Özgür','F','Tuna',26, 9);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (43,'Sporcu','Phil','T','Foden',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (44,'Sporcu','Mason','M','Mount',27, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (45,'Siber Güvenlik Mühendisliği','Sergio','L','Perez',28, 25);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (46,'Mekatronik Mühendisliği','Erol','C','Teriz',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (47,'Matematik','Emrah','H','Duman',29, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (48,'Doktor','Şenol','R','Gelir',30, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (49,'Doktor','Yusuf','F','İzler',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (50,'Pilot','Mahmut','N','Zakkum',31, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (51,'Pilot','Joseph','M','Hunter',32, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (52,'Öğretmen','Burak','P','Asker',33, 22);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (53,'Öğretmen','Orhan','A','Yaman',null, 21);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (54,'Öğretmen','Osman','M','Güleryüz',null, 27);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (55,'Mekatronik Mühendisliği','Betül','O','Göz',34, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (61,'Mekatronik Mühendisliği','Hasan','M','Tanyürek',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (62,'Sporcu','Cenk','F','Tosun',35, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (63,'Doktor','Kerim','G','Alıcı',36, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (64,'Pilot','Taşkın','N','Çalış',37, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (65,'Pilot','Kerim','M','Altı',38, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (66,'Bilgisayar Münedisliği','Okan','','Tanrıverdi',null, 3);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (67,'Danışmanlık','Ahmet','K','Burhan',null, 2);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (68,'Tarım Mühendisliği','Mahmut','','Armut',39, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (69,'Turizm','Orhan','O','Aydın',40, 16);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (70,'Makine Mühendisliği','Osman','','Durmuş',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (71,'Yazılım Mühendisliği','Safiye','','Kaplan',41, 8);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (72,'Danışmanlık','Erhan','T','Toplar',42, 6);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (73,'Matematik','Jackson','M','Big',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (74,'Bilgisayar Mühendisliği','Marissa','J','Hitch',null, 10);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (75,'Öğrenci','Emine','','Kırmızı',43, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (76,'Öğrenci','Serhat','','Beyaz',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (77,'Öğrenci','Beyza','L','Havuz',44, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (78,'Öğrenci','Ferhat','','Leylek',45, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (79,'Öğrenci','Hafize','M','Ana',46, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (80,'Öğrenci','Hakan','','Hafız',47, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (81,'Öğrenci','Metin','C','Buca',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (82,'Öğrenci','İhsan','T','Oğul',null, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (83,'Öğrenci','Hamdi','','Taş',48, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (89,'Öğrenci','Emin','','Çapa',49, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (90,'Öğrenci','Hakkı','N','Güzel',50, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (91,'Öğrenci','Pelin','K','Aykut',51, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (92,'Öğrenci','Jack','S','Port',52, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (93,'Öğrenci','Levent','A','Kılıç',53, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (94,'Öğrenci','İbrahim','','Poyraz',54, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (95,'Öğrenci','Ahmed','A','Güzel',55, 14);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (96,'Öğrenci','Owen','B','Butter',56, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (97,'Öğrenci','Muhammed','M','Kır',57, 17);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (98,'Öğrenci','Selin','','Ay',58, null);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (99,'Öğrenci','Ceyhun','R','Toprak',59, 24);
insert into Personal (acc_id, department, fname, minit, lname, addr_id, cv_id) values (100,'Öğrenci','Toprak','A','Koç',60, null);
