insert into Content(post_id, isText, text, isMedia, is_video, media) values (1, true, 'Is computer science a good major? With a median pay of $91,250 and job growth of 11% in the computer and IT field , yes, computer science is a good major.', false, false, '');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (2, false, '', true, true, 'kflsf');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (3, false, '', true, true, 'love');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (4, false, '', true, false, 'art');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (5, false, '', true, true, 'hiring');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (6, false, '', true, false, 'poster');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (7, true, 'Dear Students. Check this out!', true, true, 'dear');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (8, false, '', true, true, 'life');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (9, true, 'As a discipline, Mechanical Engineering focuses on the design, manufacturing and maintenance of machinery. This makes it an incredibly broad type of Engineering, covering everything from designing cars to building robots.', false, false, '');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (10, false, '', true, false, 'pc');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (11, true, 'Çalışacak Stajyer arıyoruz.', true, false, 'hiring');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (12, false, '', true, false, 'abc');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (13, true, 'Yeni Hazırladığımız tanıtım filmimiz:', true, true, 'zyz');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (14, false, '', true, false, 'aeqeq');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (15, true, 'Numbers Theory', true, false,'123414');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (16, false, '', true, true, 'photo1');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (17, true, 'Two of the most common types are Electrical Engineering and Electronic Engineering. Academically, they are often grouped together as a single discipline or degree.', false, false, '');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (18, false, '', true, false, 'fotoğraf1');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (19, true, 'Bugün çektiğim video', true, true, 'img_23131');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (20, false, '', true, false, 'brother');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (21, true, 'Yeni işime başladım', true, false, 'job');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (22, false, '', true, false, 'engineer');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (23, true, 'Güzel bir tanıtım filmi gördüm', true, true, '382131');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (24, false, '', true, false, 'foto');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (25, false, '', true, false, 'photo');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (26, false, '', true, true, 'with');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (27, false, '', true, false, 'shoes');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (28, true, 'Patronla yemek keyf', true, false, 'dinner');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (29, false, '', true, false, 'launch');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (30, false, '', true, true, 'homework1');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (31, true, 'Ödev için yaptığım proje:', TRUE, false, 'homework2');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (32, false, '', true, true, 'homework4');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (33, false, '', true, false, 'abcabc');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (34, true, 'I am new here :)', true, false, 'hi');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (35, true, 'İşyerimden kareler', true, true, 'my_photo');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (36, false, '', true, false, '41414141');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (37, true, 'Eating a healthy, balanced diet is one of the most important things you can do to protect your health. In fact, up to 80% of premature heart disease and stroke can be prevented through your life choices and habits, such as eating a healthy diet and being physically active.', true, true, 'share');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (38, false, '', true, false, 'xd');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (39, true, 'Eating food helps you not starve', false, false, '');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (40, true, 'Daily Tip! Work more to earn more.', false, false, '');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (41, true, 'Photo of me with my friends checking out our  factory', true, false, 'with_friends');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (42, false, '', true, true, 'my_wife');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (43, false, '', true, false, 'my_life');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (44, true, 'Im looking for a job! You can look my bio.', true, false, 'woww');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (45, true, 'That thing scares me', true, true, 'that');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (46, false, '', true, false, 'correct');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (47, true, 'Hiring more people than ever! Check us out!', true, true, 'hiring');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (48, false, '', true, false, 'art');
insert into Content(post_id, isText, text, isMedia, is_video, media) values (49, true, 'Enjoying life after long day of work', true, false, 'art');