insert into Profile (acc_id, bio) values (1, 'Co-chair, Developer');
insert into Profile (acc_id, bio) values (2, 'Chemistry expert. ,#love-animals');
insert into Profile (acc_id, bio) values (3, '100100010100101010 1010101010 10101010');
insert into Profile (acc_id, bio) values (4, 'Bzzt carefull :)');
insert into Profile (acc_id, bio) values (5, 'Eat healty foods !!!');
insert into Profile (acc_id, bio) values (6, 'Planting is important');
insert into Profile (acc_id, bio) values (7, 'Chemistry is my job :)');
insert into Profile (acc_id, bio) values (8, '#Love-sharing #Love-Animals');
insert into Profile (acc_id, bio) values (9, 'Front-end Developer. For Business: +905381297189');
insert into Profile (acc_id, bio) values (10, 'Gıda diyip geçmee');
insert into Profile (acc_id, bio) values (11, 'Bzzzzzzt!!!!');
insert into Profile (acc_id, bio) values (12, '#Working7/24...');
insert into Profile (acc_id, bio) values (13, 'Looking for job...');
insert into Profile (acc_id, bio) values (14, 'Hey,Siri!....Where is my job?');
insert into Profile (acc_id, bio) values (15, 'C6H12C4 for life:)');
insert into Profile (acc_id, bio) values (16, 'H2+ 1/2 O2 = H20');
insert into Profile (acc_id, bio) values (17, 'Java,C#,C');
insert into Profile (acc_id, bio) values (18, '#Eating-Healty');
insert into Profile (acc_id, bio) values (19, 'Peysaj Mühendisi');
insert into Profile (acc_id, bio) values (20, 'Peysaj bizim işimiz:)');
insert into Profile (acc_id, bio) values (21, 'Gıda Mühendisi, 3 Çocuk Babası');
insert into Profile (acc_id, bio) values (22, 'Chemistry is fun!');
insert into Profile (acc_id, bio) values (23, 'Chemistry for life!!');
insert into Profile (acc_id, bio) values (24, 'F=ma :)');
insert into Profile (acc_id, bio) values (25, 'İtü Çevre Mühendisliği Mezunu (İş arıyorrr)');
insert into Profile (acc_id, bio) values (26, '#Animals #Plants #Love #Share');
insert into Profile (acc_id, bio) values (27, 'Çevre Her Şeydir');
insert into Profile (acc_id, bio) values (28, 'Chemistry Expert');
insert into Profile (acc_id, bio) values (29, 'Organik Kimyam');
insert into Profile (acc_id, bio) values (30, 'İş = F.x');
insert into Profile (acc_id, bio) values (31, 'Matematik-1999');
insert into Profile (acc_id, bio) values (32, 'Mehmet Güleryüz resmi hesap.');
insert into Profile (acc_id, bio) values (33, 'Pilot since 2001');
insert into Profile (acc_id, bio) values (34, 'Ali Akman offical');
insert into Profile (acc_id, bio) values (35, 'Dr.Callum');
insert into Profile (acc_id, bio) values (36, 'Engineer');
insert into Profile (acc_id, bio) values (37, 'Work hard!');
insert into Profile (acc_id, bio) values (38, 'Sleepy everytime -- ');
insert into Profile (acc_id, bio) values (39, 'Investor');
insert into Profile (acc_id, bio) values (40, 'Developer');
insert into Profile (acc_id, bio) values (41, 'Busy all the time..');
insert into Profile (acc_id, bio) values (42, 'Teacher');
insert into Profile (acc_id, bio) values (43, 'FOUNDER OF PULL AND BEAR');
insert into Profile (acc_id, bio) values (44, 'CEO HS Yazılım ');
insert into Profile (acc_id, bio) values (45, 'Head of CocaCola');
insert into Profile (acc_id, bio) values (46, 'Loving life!');
insert into Profile (acc_id, bio) values (47, '05.01.1998');
insert into Profile (acc_id, bio) values (48, 'Doktor Şenol Gelir');
insert into Profile (acc_id, bio) values (49, 'Op.DR.YUSUF İZLER');
insert into Profile (acc_id, bio) values (50, 'vsco.com/mahmutzakkum');
insert into Profile (acc_id, bio) values (51, 'Chill bro.');
insert into Profile (acc_id, bio) values (52, 'My Only Account!');
insert into Profile (acc_id, bio) values (53, 'No words left to say..');
insert into Profile (acc_id, bio) values (54, 'vsco.com/osmanguleryuz');
insert into Profile (acc_id, bio) values (55, 'Hi there!');
insert into Profile (acc_id, bio) values (56, 'Intel Official');
insert into Profile (acc_id, bio) values (57, 'Arçelik resmi hesabıdır.');
insert into Profile (acc_id, bio) values (58, 'Since 1985 best ice cream for u.');
insert into Profile (acc_id, bio) values (59, 'PullAndBear official account.');
insert into Profile (acc_id, bio) values (60, 'Best coke.');
insert into Profile (acc_id, bio) values (61, 'Mekatronik Müzhendisi. #mekatronik4Life');
insert into Profile (acc_id, bio) values (62, 'Milli Sporcu. Fitness Coach. DM for info');
insert into Profile (acc_id, bio) values (63, 'Doctor at Ege University. #health');
insert into Profile (acc_id, bio) values (64, 'Pilot at THY. I fly everywhere');
insert into Profile (acc_id, bio) values (65, 'Pilot. Currently a instructor but no course :)');
insert into Profile (acc_id, bio) values (66, 'Bilgisayar müh. #boring');
insert into Profile (acc_id, bio) values (67, '#danış Personal Danışmanlık CEO');
insert into Profile (acc_id, bio) values (68, '#tarımhayattır. Tarım mühendisi. ');
insert into Profile (acc_id, bio) values (69, 'Turizm. Come to malatya');
insert into Profile (acc_id, bio) values (70, '');
insert into Profile (acc_id, bio) values (71, 'Owner of Brake Software. #buildthefuture');
insert into Profile (acc_id, bio) values (72, 'Done my doctorate 8) Instructor.');
insert into Profile (acc_id, bio) values (73, 'Maeth is fun when you snort :)');
insert into Profile (acc_id, bio) values (74, 'Hi guys. Welcome to my bio. I love COMPUTERS. Owner of Matrix Software');
insert into Profile (acc_id, bio) values (75, 'Deciple of Kerim Aslan.');
insert into Profile (acc_id, bio) values (76, 'Student. Keen to work.');
insert into Profile (acc_id, bio) values (77, 'Havuz profu');
insert into Profile (acc_id, bio) values (78, 'Interested in animals. Maybe too much');
insert into Profile (acc_id, bio) values (79, 'History rocks!');
insert into Profile (acc_id, bio) values (80, '');
insert into Profile (acc_id, bio) values (81, 'Bucalı...');
insert into Profile (acc_id, bio) values (82, '#lookingforwork');
insert into Profile (acc_id, bio) values (83, 'Student. At the middle of the road');
insert into Profile (acc_id, bio) values (84, 'HS Yazılım. We build future.');
insert into Profile (acc_id, bio) values (85, 'Kızıl boyacılık. Boya bizden sorulur.');
insert into Profile (acc_id, bio) values (86, 'Danışmanlık bizim işimiz. Danışın çözelim...');
insert into Profile (acc_id, bio) values (87, 'Brake Software.');
insert into Profile (acc_id, bio) values (88, 'Matrix Software just like the movie');
insert into Profile (acc_id, bio) values (89, 'dm for business: ');
insert into Profile (acc_id, bio) values (90, 'memories');
insert into Profile (acc_id, bio) values (91, 'fx=mylife');
insert into Profile (acc_id, bio) values (92, 'Have a dream..');
insert into Profile (acc_id, bio) values (93, 'im here for money -');
insert into Profile (acc_id, bio) values (94, 'i feel it coming...');
insert into Profile (acc_id, bio) values (95, 'vsco.com/ahmedguzel');
insert into Profile (acc_id, bio) values (96, 'Cloudy..');
insert into Profile (acc_id, bio) values (97, 'In Your Eyes...');
insert into Profile (acc_id, bio) values (98, 'Set me free');
insert into Profile (acc_id, bio) values (99, 'print(Helloworld)');
insert into Profile (acc_id, bio) values (100, 'Counting the stars.');