insert into Enrolls(student_id, course_id, enroll_key) values (99, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (93, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (94, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (95, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (96, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (97, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (98, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (99, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (100, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (93, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (94, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (95, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (96, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (97, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (98, 2, 'calculus2022');
insert into Enrolls(student_id, course_id, enroll_key) values (100, 1, 'intro_chemistry22');
insert into Enrolls(student_id, course_id, enroll_key) values (89, 4, 'y90xyIHdDASFzlLzr');
insert into Enrolls(student_id, course_id, enroll_key) values (90, 4, 'y90xyIHdDASFzlLzr');
insert into Enrolls(student_id, course_id, enroll_key) values (91, 4, 'y90xyIHdDASFzlLzr');
insert into Enrolls(student_id, course_id, enroll_key) values (92, 4, 'y90xyIHdDASFzlLzr');
insert into Enrolls(student_id, course_id, enroll_key) values (75,3, 'dbmanagement_22');
insert into Enrolls(student_id, course_id, enroll_key) values (76,3, 'dbmanagement_22');
insert into Enrolls(student_id, course_id, enroll_key) values (77,3, 'dbmanagement_22');
insert into Enrolls(student_id, course_id, enroll_key) values (78,3, 'dbmanagement_22');
insert into Enrolls(student_id, course_id, enroll_key) values (79,3, 'dbmanagement_22');
insert into Enrolls(student_id, course_id, enroll_key) values (80,3, 'dbmanagement_22');
insert into Enrolls(student_id, course_id, enroll_key) values (81,4, 'y90xyIHdDASFzlLzr');
insert into Enrolls(student_id, course_id, enroll_key) values (82,4, 'y90xyIHdDASFzlLzr');
insert into Enrolls(student_id, course_id, enroll_key) values (83,4, 'y90xyIHdDASFzlLzr');