insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (80, 67, 'Merhaba.');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (80, 67, 'Size danışmak istiyordum.');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (67, 80, 'Ne konuda?');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (80, 67, 'Mühendislikte hangi yoldan gitmek istediğime karar vermedim.');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (67, 80, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (67, 80, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (80, 67, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (80, 67, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (67, 80, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (80, 67, 'Cevap için teşekkürler.');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (17, 23, 'Merhaba');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (23, 17, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (22, 88, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (98, 12, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (3, 38, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (19, 57, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (24, 78, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (5, 45, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (54, 8, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (87, 7, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (8, 37, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (38, 65, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (43, 35, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (13, 76, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (74, 67, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (78, 73, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (78, 4, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (93, 86, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (4, 57, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (75,42 , '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (7, 45, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (78, 79, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (9, 66, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (72, 66, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (2, 33, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (44, 100, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (2, 11, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (33, 55, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (88, 6, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (55, 50, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (70, 90, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (20, 15, '...');
insert into Messages(sender_acc_id, receive_acc_id, msg_text) values (35, 66, '...');