insert into Post(post_owner_id, isGroup) values (1, false);
insert into Post(post_owner_id, isGroup) values (3, false);
insert into Post(post_owner_id, isGroup) values (4, false);
insert into Post(post_owner_id, isGroup) values (5, false);
insert into Post(post_owner_id, isGroup) values (8, false);
insert into Post(post_owner_id, isGroup) values (10, false);
insert into Post(post_owner_id, isGroup) values (12, false);
insert into Post(post_owner_id, isGroup) values (14, false);
insert into Post(post_owner_id, isGroup) values (17, false);
insert into Post(post_owner_id, isGroup) values (20, false);
insert into Post(post_owner_id, isGroup) values (33, false);
insert into Post(post_owner_id, isGroup) values (34, false);
insert into Post(post_owner_id, isGroup) values (35, false);
insert into Post(post_owner_id, isGroup) values (36, false);
insert into Post(post_owner_id, isGroup) values (37, false);
insert into Post(post_owner_id, isGroup) values (38, false);
insert into Post(post_owner_id, isGroup) values (39, false);
insert into Post(post_owner_id, isGroup) values (45, false);
insert into Post(post_owner_id, isGroup) values (55, false);
insert into Post(post_owner_id, isGroup) values (67, false);
insert into Post(post_owner_id, isGroup) values (68, false);
insert into Post(post_owner_id, isGroup) values (69, false);
insert into Post(post_owner_id, isGroup) values (70, false);
insert into Post(post_owner_id, isGroup) values (71, false);
insert into Post(post_owner_id, isGroup) values (72, false);
insert into Post(post_owner_id, isGroup) values (73, false);
insert into Post(post_owner_id, isGroup) values (74, false);
insert into Post(post_owner_id, isGroup) values (75, false);
insert into Post(post_owner_id, isGroup) values (76, false);
insert into Post(post_owner_id, isGroup) values (92, false);
insert into Post(post_owner_id, isGroup) values (93, false);
insert into Post(post_owner_id, isGroup) values (94, false);
insert into Post(post_owner_id, isGroup) values (95, false);
insert into Post(post_owner_id, isGroup) values (96, false);

#Gruplarda paylaşılan Postlar
insert into Post(isGroup, group_id, post_owner_id) values (true, 1, 71);
insert into Post(isGroup, group_id, post_owner_id) values (true, 1,74);
insert into Post(isGroup, group_id, post_owner_id) values (true, 1, 1);
insert into Post(isGroup, group_id, post_owner_id) values (true, 2, 34);
insert into Post(isGroup, group_id, post_owner_id) values (true, 2, 36);
insert into Post(isGroup, group_id, post_owner_id) values (true, 2, 40);
insert into Post(isGroup, group_id, post_owner_id) values (true, 3, 95);
insert into Post(isGroup, group_id, post_owner_id) values (true, 3, 96);
insert into Post(isGroup, group_id, post_owner_id) values (true, 3, 97);
insert into Post(isGroup, group_id, post_owner_id) values (true, 5, 20);
insert into Post(isGroup, group_id, post_owner_id) values (true, 5, 21);
insert into Post(isGroup, group_id, post_owner_id) values (true, 5, 22);
insert into Post(isGroup, group_id, post_owner_id) values (true, 6, 5);
insert into Post(isGroup, group_id, post_owner_id) values (true, 6, 9);
insert into Post(isGroup, group_id, post_owner_id) values (true, 6, 11);